In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv",index_col=0)

In [3]:
matches.head(10)

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2023,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2023,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2023,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2023,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2023,Manchester City
6,2022-09-03,17:30,Premier League,Matchweek 6,Sat,Away,D,1,1,Aston Villa,...,Match Report,NaN,13.0,4.0,16.8,1.0,0.0,0.0,2023,Manchester City
9,2022-09-17,12:30,Premier League,Matchweek 8,Sat,Away,W,3,0,Wolves,...,Match Report,NaN,16.0,7.0,19.4,0.0,0.0,0.0,2023,Manchester City
10,2022-10-02,14:00,Premier League,Matchweek 9,Sun,Home,W,6,3,Manchester Utd,...,Match Report,NaN,22.0,9.0,14.2,1.0,0.0,0.0,2023,Manchester City
12,2022-10-08,15:00,Premier League,Matchweek 10,Sat,Home,W,4,0,Southampton,...,Match Report,NaN,21.0,8.0,13.9,0.0,0.0,0.0,2023,Manchester City
14,2022-10-16,16:30,Premier League,Matchweek 11,Sun,Away,L,0,1,Liverpool,...,Match Report,NaN,16.0,6.0,18.4,0.0,0.0,0.0,2023,Manchester City

In [4]:
matches["Date"] = pd.to_datetime(matches["Date"])
matches.dtypes

Date            datetime64[ns]
Time                    object
Comp                    object
Round                   object
Day                     object
Venue                   object
Result                  object
GF                       int64
GA                       int64
Opponent                object
xG                     float64
xGA                    float64
Poss                   float64
Attendance             float64
Captain                 object
Formation               object
Referee                 object
Match Report            object
Notes                  float64
Sh                     float64
SoT                    float64
Dist                   float64
FK                     float64
PK                     float64
PKatt                  float64
Season                   int64
Team                    object
dtype: object

In [5]:
matches["Venue_Code"] = matches["Venue"].astype("category").cat.codes
matches["Opp_Code"] = matches["Opponent"].astype("category").cat.codes
matches["Hour"] = matches["Time"].str.replace(":.+","",regex=True).astype("int")
matches["Day_Code"] = matches["Date"].dt.day_of_week
matches["Target"] = (matches["Result"]=="W").astype("int")
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,Venue_Code,Opp_Code,Hour,Day_Code,Target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,1.0,1.0,1.0,2023,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,0.0,0.0,0.0,2023,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,1.0,0.0,0.0,2023,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,0.0,0.0,0.0,2023,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,0.0,0.0,0.0,2023,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0,4,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,20,19,6,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,1,7,15,5,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1,0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,0,8,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,15,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1,0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,5,16,6,1

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [75]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [76]:
from sklearn.metrics import precision_score

In [13]:
grouped_matches = matches.groupby("Team")

In [14]:
def rolling_averages(group,cols,new_cols):
    group = group.sort_values("Date")
    rolling_stats = group[cols].rolling(3,closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

cols = ['GF','GA','Sh','SoT','Dist','FK','PK','PKatt']
new_cols = [f"{c}_rolling" for c in cols]

In [15]:
matches_rolling = grouped_matches.apply(lambda x: rolling_averages(x,cols,new_cols))
matches_rolling = matches_rolling.droplevel("Team")
matches_rolling.index = range(matches_rolling.shape[0])

In [82]:
matches_rolling

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Day_Code,Target,GF_rolling,GA_rolling,Sh_rolling,SoT_rolling,Dist_rolling,FK_rolling,PK_rolling,PKatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2197,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0,6,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
2198,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1,0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
2199,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0,2,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
2200,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1,1,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
2201,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [83]:
def make_predictions(data,predictors):
    train =data[data["Date"] < '2022-12-07']
    test = data[data["Date"] > '2022-12-07']
    rf.fit(train[predictors],train["Target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["Target"],prediction=preds),index=test.index)
    precision = precision_score(test["Target"],preds)
    return combined,precision

In [84]:
combined,precision = make_predictions(matches_rolling,predictors+new_cols)
combined

      actual  prediction
87         1           0
88         1           1
89         0           1
90         1           1
91         1           0
...      ...         ...
2197       0           0
2198       1           0
2199       0           0
2200       0           0
2201       0           0

[468 rows x 2 columns]

In [85]:
combined = combined.merge(matches_rolling[["Date",'Team','Opponent','Result']],left_index=True,right_index=True)
combined

,actual,prediction,Date,Team,Opponent,Result
87,1,0,2022-12-26,Arsenal,West Ham,W
88,1,1,2022-12-31,Arsenal,Brighton,W
89,0,1,2023-01-03,Arsenal,Newcastle Utd,D
90,1,1,2023-01-15,Arsenal,Tottenham,W
91,1,0,2023-01-22,Arsenal,Manchester Utd,W
...,...,...,...,...,...,...
2197,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L
2198,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W
2199,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L
2200,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D
2201,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L

In [63]:
precision

0.5688073394495413

In [86]:
class MissingDict(dict):
    __missing__ = lambda self, key:key

map_values = {
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle United": "Newcastle Utd",
    "Sheffield United": "Sheffield Utd",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
    "Nottingham Forest": "Nott'ham Forest",
    "West Bromwich Albion": "West Brom"
}

mapping = MissingDict(**map_values)

In [88]:
combined["New_Team"] = combined["Team"].map(mapping)
combined

,actual,prediction,Date,Team,Opponent,Result,New_Team
87,1,0,2022-12-26,Arsenal,West Ham,W,Arsenal
88,1,1,2022-12-31,Arsenal,Brighton,W,Arsenal
89,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal
90,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal
91,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal
...,...,...,...,...,...,...,...
2197,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
2198,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves
2199,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves
2200,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves
2201,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves

In [89]:
merged = combined.merge(combined,left_on=["Date","New_Team"],right_on=["Date","Opponent"])
merged

,actual_x,prediction_x,Date,Team_x,Opponent_x,Result_x,New_Team_x,actual_y,prediction_y,Team_y,Opponent_y,Result_y,New_Team_y
0,1,0,2022-12-26,Arsenal,West Ham,W,Arsenal,0,0,West Ham United,Arsenal,L,West Ham
1,1,1,2022-12-31,Arsenal,Brighton,W,Arsenal,0,0,Brighton and Hove Albion,Arsenal,L,Brighton
2,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
3,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
4,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,1,Manchester United,Arsenal,L,Manchester Utd
...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
464,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
465,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,0,Manchester United,Wolves,W,Manchester Utd
466,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,1,Everton,Wolves,D,Everton
467,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal

In [72]:
merged[(merged["prediction_x"]==1) & (merged["prediction_y"]==0)]["actual_x"].value_counts()

1    58
0    41
Name: actual_x, dtype: int64

In [91]:
Precision = 58/(58+41)
Precision

0.5858585858585859